using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace EzBusiness_EF_Entity
{
    public partial class FixedAsset
    {
        public string Cmpycode { get; set; }
        public string SelfGenCode { get; set; }
        public string AssetCode { get; set; }
        public string CompanyCode { get; set; }
        public string CompanyName { get; set; }
        public string AssetTypeCode { get; set; }
        public string AssetType { get; set; }
        public string AssetCategoryCode { get; set; }
        public string AssetCategory { get; set; }
        public string AssetSubCategoryCode { get; set; }
        public string AssetSubCategory { get; set; }
        public string AssetName { get; set; }
        public string GroupCode { get; set; }
        public string LocCode { get; set; }
        public string ProjectCode { get; set; }
        public string Fleet { get; set; }
        public string SIZE { get; set; }
        public string CostAc { get; set; }
        public string DepAc { get; set; }
        public string DepNo { get; set; }
        public string MGROUP { get; set; }
        public string SGROUP { get; set; }
        public string Brand { get; set; }
        public string Origin { get; set; }
        public string YearMade { get; set; }
        public string Model { get; set; }
        public string Color { get; set; }
        public string EngineNo { get; set; }
        public string ChasisNo { get; set; }
        public string Notes { get; set; }
        public string SupplierCode { get; set; }
        public Nullable<System.DateTime> PurDate { get; set; }
        public string PurRef { get; set; }
        public decimal IntCost { get; set; }
        public string CurrencyCode { get; set; }
        public decimal OrigCost { get; set; }
        public decimal AddCost { get; set; }
        public decimal CurrentCost { get; set; }
        public string RegNo { get; set; }
        public string RegName { get; set; }
        public Nullable<System.DateTime> RegBegin { get; set; }
        public Nullable<System.DateTime> RegEnd { get; set; }
        public string Driver { get; set; }
        public string InsCo { get; set; }
        public string PolicyType { get; set; }
        public string PolicyNo { get; set; }
        public Nullable<System.DateTime> InsBegin { get; set; }
        public Nullable<System.DateTime> InsEnd { get; set; }
        public decimal InvValue { get; set; }
        public decimal InsPremium { get; set; }
        public string InsType { get; set; }
        public decimal LastDep { get; set; }
        public decimal ResVal { get; set; }
        public decimal DepVal { get; set; }
        public string DepUnit { get; set; }
        public decimal UseLife { get; set; }
        public decimal TotUsed { get; set; }
        public decimal DepPremium { get; set; }
        public decimal MonDep { get; set; }
        public decimal OpenDep { get; set; }
        public decimal TotDep { get; set; }
        public Nullable<System.DateTime> DepBegin { get; set; }
        public decimal NetVal { get; set; }
        public decimal CurrentDepr { get; set; }
        public decimal OAmt { get; set; }
        public decimal CAmt { get; set; }
        public string Disposed { get; set; }
        public string LGroup { get; set; }
        public string DeptCode { get; set; }
        public string EmpCode { get; set; }
        public string AssetStatus { get; set; }
        public string Criticality { get; set; }
        public string WC { get; set; }
        public string WarrentyContractNo { get; set; }
        public Nullable<System.DateTime> WarrentyExpDate { get; set; }
        public string Manufacturer { get; set; }
        public string AssetNote { get; set; }
        public Nullable<System.DateTime> DateDisposed { get; set; }
        public int Levels { get; set; }
        public string SubOf { get; set; }
        public string SerialNo { get; set; }
        public decimal Capacity { get; set; }
        public string Unit { get; set; }
        public string Remarks { get; set; }
        public decimal OTrate { get; set; }
        public decimal SBrate { get; set; }
        public decimal WSrate { get; set; }
        public decimal NRate { get; set; }
        public decimal FuelConsRate { get; set; }
        public string LoginUser { get; set; }
        public string Type { get; set; }
        public string VehicleType { get; set; }
        public string VehicleModel { get; set; }
        public string EngineType { get; set; }
        public string CustomerCode { get; set; }
        public string UnitNo { get; set; }
        public string Years { get; set; }
        public string Make { get; set; }
        public string SerialVIN { get; set; }
        public string PlateNo { get; set; }
        public string Identification { get; set; }
        public string MeterType { get; set; }
        public string CurMileage { get; set; }
        public string BaseMileage { get; set; }
        public Nullable<System.DateTime> BaseDate { get; set; }
        public string DriverName { get; set; }
        public string oilFilterType { get; set; }
        public string GrossWeight { get; set; }
        public string Lenght { get; set; }
        public string Width { get; set; }
        public string Height { get; set; }
        public string Wheelbase { get; set; }
        public string AxlesNo { get; set; }
        public string TireSizeF { get; set; }
        public string TireSizeR { get; set; }
        public string WiperBladeL { get; set; }
        public string WiperBladeR { get; set; }
        public string EngineSize { get; set; }
        public string Cylinders { get; set; }
        public string transmissionType { get; set; }
        public string FuelType { get; set; }
        public string AirFilterIN { get; set; }
        public string EngineSLN { get; set; }
        public string Runby { get; set; }
        public string TotalMaint { get; set; }
        public string PreviousProject { get; set; }
        public string SeatCap { get; set; }
        public string AirFilterOUT { get; set; }
        public string HydType { get; set; }
        public decimal CurRate { get; set; }
        public string EnableReminder { get; set; }
        public decimal ReminderBeforeDay { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Agent { get; set; }
        public string AgentPhone { get; set; }
        public decimal LifePeriod { get; set; }
        public string FixedAsset1 { get; set; }
        public decimal StartingDep { get; set; }
        public string OldRegNo { get; set; }
        public string OldFleetNo { get; set; }
        public decimal HourlyRate { get; set; }
        public decimal MaximumHourToBeWorked { get; set; }
        public string checkInOUT { get; set; }
        public string Ref_AssetCode { get; set; }
        public string MortageCode { get; set; }
        public Nullable<System.DateTime> MortageStartDate { get; set; }
        public Nullable<System.DateTime> MortageEndDate { get; set; }
        public decimal MortalInstallment { get; set; }
        public string Section { get; set; }
        public decimal Basecost { get; set; }
        public decimal OtherCost { get; set; }
        public decimal TotalCost { get; set; }
        public decimal NumberMade { get; set; }
        public string BarCodeNo { get; set; }
        public decimal Quantity { get; set; }
        public string Shape { get; set; }
        public string NotDepreciable { get; set; }
        public decimal OT_Rate { get; set; }
        public decimal HOT_Rate { get; set; }
        public decimal Trip_Rate { get; set; }
        public string MakeEquipmentLogsheet { get; set; }
        public string BillingYN { get; set; }
        public string RateFactor { get; set; }
        public decimal PurchasePriceLocal { get; set; }
        public string TagNumber { get; set; }
        public decimal OvertimeRate { get; set; }
        public decimal Fridayrate { get; set; }
        public decimal Mcost { get; set; }
        public decimal Dcost { get; set; }
        public decimal TripRate { get; set; }
        public decimal HrsMileageExpiry { get; set; }
        public string PProjectCode { get; set; }
        public decimal Lumpsumcost { get; set; }
        public string DeliveryNoteNo { get; set; }
        public Nullable<System.DateTime> DeliveryNoteDate { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public decimal PurchasePriceAED { get; set; }
        public string ROOMREF { get; set; }
        public Nullable<System.DateTime> LastDepreciationDate { get; set; }
        public string Ssub { get; set; }
        public decimal A_deprAmount { get; set; }
        public decimal C_deprAmount { get; set; }
        public int DirectCreated { get; set; }
        public string RentingStatus { get; set; }
        public string AssetClass { get; set; }
        public decimal FreeMilesPerDay { get; set; }
        public decimal RatePerExtraMiles { get; set; }
        public decimal Amount { get; set; }
        public string GRNRef { get; set; }
        public Nullable<System.DateTime> LPODate { get; set; }
        public string ShowInReport { get; set; }
        public string FuelCard { get; set; }
        public decimal AccDep { get; set; }
        public decimal Limit { get; set; }
        public string Allow { get; set; }
        public decimal GVW { get; set; }
        public string Nationality { get; set; }
        public string TCNo { get; set; }
        public string MortgageBy { get; set; }
        public string GroupCurrent { get; set; }
    }
}
